spring:
  api-limit:
    enabled: false
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 200
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB

  lifecycle:
    timeout-per-shutdown-phase: 30s

storage:
  bucket: lang-thang-assets

application:
  image:
    support-type: image/png,image/jpg,image/jpeg,image/webp

  broker:
    prefix: /topic
    end-point: /socket-server
    notify:
      prefix: ${application.broker.prefix}/notify
    post:
      prefix: ${application.broker.prefix}/post
  server:
    url: ${HOST:https://langthang.trinhdvt.tech}

server:
  compression:
    enabled: true
  port: ${PORT:8080}
  servlet:
    context-path: /api
  shutdown: graceful

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        stat: DEBUG
        SQL_SLOW: INFO
    com:
      langthang: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: com.langthang.controller.v2

