apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
        - name: langthangv2
          image: trinhvideo123/langthang:v2
          ports:
            - containerPort: 8080
          resources: { }
          envFrom:
            - secretRef:
                name: langthang-prod-env

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 8080
  selector:
    service: backend
