const ACTIONS = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',

    //GET COMMENTS PAGE 0
    GET_COMMENTS: 'GET_COMMENTS',
    GET_NEXT_COMMENTS_PAGE: 'GET_NEXT_COMMENTS_PAGE', 
    EMPTY_COMMENT: 'EMPTY_COMMENT',
    SUBMIT_COMMENT: 'SUBMIT_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    EDIT_COMMENT: 'EDIT_COMMENT',
    LIKE_COMMENT: 'LIKE_COMMENT',
    COMMENT_ERROR: 'COMMENT_ERROR',
    LOADING_COMMENT: 'LOADING_COMMENT', 
    ADD_COMMENT: 'ADD_COMMENT',
    CLEAR_COMMENT: 'CLEAR_COMMENT',

    INCREASE_NOTI: 'INCREASE_NOTI',
    DECREASE_NOTI: 'DECREASE_NOTI',
    GET_COUNT_NOTI: 'GET_COUNT_NOTI',
    REMOVE_COUNT_NOTI: 'REMOVE_COUNT_NOTI',

    SET_REALTIME_WS: 'SET_REALTIME_WS',
    SET_REALTIME_NOTI: 'SET_REALTIME_NOTI',
    REMOVE_REALTIME_NOTI: 'REMOVE_REALTIME_NOTI',
    SET_REALTIME_POST : 'SET_REALTIME_POST',
    REMOVE_REALTIME_POST: 'REMOVE_REALTIME_POST',
    CLEAR_REALTIME: 'CLEAR_REALTIME'

}

export default ACTIONS